# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 784433aec0fc81691fd0a80c69531ee1a90bf2c06e88108c32eb9e80c29c80fe8299fd227b2ddc728a2f453a26fe07e813040bc875ddbd541a19ee8ed88cb8ed

test:
  secret_key_base: 4f02bc008c8002d4c7cfd6e61afd162a81b5dd84074950111992bd5c3cff4085d0bedb4754cb5668aa632d62225d16cd6be4a734f14e31da7c3aa88513ef0224

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
